# Theme: xoff
# Source: https://github.com/zsxoff/xoff-theme

[colors.primary]
background = "#000000"
foreground = "#FFFFFF"

[colors.cursor]
cursor = "#FFFFFF"

[colors.selection]
text       = "CellForeground"
background = "#0CFA66"

[colors.normal]
black   = "#000000"
red     = "#FA3B05"
green   = "#0CFA66"
yellow  = "#FFE605"
blue    = "#15C1FF"
magenta = "#FA0474"
cyan    = "#82FAF4"
white   = "#A6A6A6"

[colors.bright]
black   = "#555555"
red     = "#FF6136"
green   = "#4BCE4F"
yellow  = "#FFF48C"
blue    = "#88BBCE"
magenta = "#FF54A1"
cyan    = "#BEFFFC"
white   = "#FFFFFF"
